name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "📄 Documentation"
    labels:
      - "documentation"
  - title: "🚀 Features"
    labels:
      - "enhancement"
  - title: "🧰 Maintenance"
    label: "chore"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

autolabeler:
  - label: "bug"
    branch:
      - '/^(bug|fix|bugfix)\/.+/'
    title:
      - "/^(bug|fix|bugfix):.+/"
  - label: "chore"
    branch:
      - '/^(chore)\/.+/'
    title:
      - "/^(chore):.+/"
  - label: "documentation"
    branch:
      - '/^(docs?|documentation)\/.+/'
    files:
      - "*.md"
    title:
      - "/^(docs?|documentation):.+/"
  - label: "enhancement"
    branch:
      - '/^(feat|feature|enhancement)\/.+/'
    title:
      - "/^(feat|feature|enhancement):.+/"

  # version-resolver labels
  # if a PR only fixes some bugs the patch should be updated
  - label: "patch"
    branch:
      - '/^(fix)\/.+/'
      - '/^(chore)\/.+/'
    title:
      - "/^(bug|fix|bugfix):.+/"
      - "/^(chore):.+/"
  # if a PR adds a feature the minor should be updated (when no breaking changes)
  - label: "minor"
    branch:
      - '/^(feat|feature|enhancement)\/.+/'
    title:
      - "/^(feat|feature|enhancement):.+/"
  # if a PR adds a breaking-change feature the major should be updated
  - label: "major"
    body:
      - '/BREAKING\ CHANGE/'

exclude-labels:
  - "skip-changelog"

template: |
  ## Changes

  $CHANGES
